Repository akshitagit/CPP, pull requests merged in 2020-10, with the labels that each got.

#512 Added greedy algorithm: Minimum coins
  Greedy/minCoins.cpp
Labels: algorithms, hacktoberfest

#500 adding some famous DP Problems on Trees
  Dynamic_Programming/DiameterOfBinaryTree.cpp
  Dynamic_Programming/MaxPathSumFromLeafToAnyLeaf.cpp
  Dynamic_Programming/MaxPathSumFromNodeToAnyNode.cpp
Labels: hacktoberfest

#338 AVL tree implementation
  Trees/AVLTREE.C
Labels: hacktoberfest-accepted
